const Cm = () => {
    return (
        <div>
            <table cellPadding='0' cellSpacing='0'>
                <thead>
                    <tr>
                        <th>SIZE</th>
                        <th>CHEST</th>
                        <th>LENGTH</th>
                        <th>SHOULDER</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>S</th>
                        <th>89</th>
                        <th>66</th>
                        <th>43</th>
                    </tr>
                    <tr>
                        <th>M</th>
                        <th>101</th>
                        <th>68</th>
                        <th>46</th>
                    </tr>
                    <tr>
                        <th>L</th>
                        <th>106</th>
                        <th>71</th>
                        <th>48</th>
                    </tr>
                    <tr>
                        <th>XL</th>
                        <th>112</th>
                        <th>73</th>
                        <th>51</th>
                    </tr>
                    <tr>
                        <th>2XL</th>
                        <th>117</th>
                        <th>76</th>
                        <th>53</th>
                    </tr>
                    <tr>
                        <th>3XL</th>
                        <th>122</th>
                        <th>79</th>
                        <th>56</th>
                    </tr>
                    <tr>
                        <th>4XL</th>
                        <th>129</th>
                        <th>79</th>
                        <th>58</th>
                    </tr>
                    <tr>
                        <th>5XL</th>
                        <th>137</th>
                        <th>79</th>
                        <th>61</th>
                    </tr>
                </tbody>
            </table>
        </div>
    );
}

export default Cm;
