const Inch = () => {
    return (
        <div>
            <table cellPadding='0' cellSpacing='0'>
                <thead>
                    <tr>
                        <th>SIZE</th>
                        <th>CHEST</th>
                        <th>LENGTH</th>
                        <th>SHOULDER</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>S</th>
                        <th>36</th>
                        <th>26</th>
                        <th>17</th>
                    </tr>
                    <tr>
                        <th>M</th>
                        <th>40</th>
                        <th>27</th>
                        <th>18</th>
                    </tr>
                    <tr>
                        <th>L</th>
                        <th>42</th>
                        <th>28</th>
                        <th>19</th>
                    </tr>
                    <tr>
                        <th>XL</th>
                        <th>44</th>
                        <th>29</th>
                        <th>20</th>
                    </tr>
                    <tr>
                        <th>2XL</th>
                        <th>46</th>
                        <th>30</th>
                        <th>21</th>
                    </tr>
                    <tr>
                        <th>3XL</th>
                        <th>48</th>
                        <th>31</th>
                        <th>22</th>
                    </tr>
                    <tr>
                        <th>4XL</th>
                        <th>52</th>
                        <th>31</th>
                        <th>23</th>
                    </tr>
                    <tr>
                        <th>5XL</th>
                        <th>54</th>
                        <th>31</th>
                        <th>24</th>
                    </tr>
                </tbody>
            </table>
        </div>
    );
}

export default Inch;
